language: node_js
node_js:
- 6.10.3
cache:
  directories:
  - node_modules
after_success:
  - npm run test
deploy:
  - provider: lambda
    function_name: "hello"
    region: "$AWS_DEFAULT_REGION"
    role: "arn:aws:iam::410064119746:role/lambda_basic_execution"
    runtime: "nodejs6.10"
    handler_name: "handler"
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_KEY"
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^master|develop$"
  - provider: lambda
    function_name: "info"
    region: "$AWS_DEFAULT_REGION"
    role: "arn:aws:iam::410064119746:role/lambda_basic_execution"
    runtime: "nodejs6.10"
    handler_name: "info"
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_KEY"
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^master|develop$"
