language: node_js
node_js:
- 6.10.3
cache:
  directories:
  - node_modules
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
after_success:
  - npm run test
deploy:
  provider: lambda
  function_name: "hello"
  region: "us-east-2"
  role: "arn:aws:iam::410064119746:role/lambda_basic_execution"
  runtime: "nodejs6.10"
  handler_name: "handler"
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_KEY"
notifications:
  slack:
    secure: f66JDRBZz2kmpbyHN7PyVrvNe+jKt50n1Fd0Icwn8L5rO5RksK9ooHAhOTaAfaWrNQidpU4+PbYe6hr9hwwVRJ2De2c9oPI5sYLt4PCLxB4JxP4IcEgNDmcOcYjI+KI2uC4ARUPtsc5DY2p7TZS+wBOn85P6/Y27NFB3xoCJNGLYXO4SFCskSD58C+Zw8CCgHEnKaRYC0OSnZhUE+hplOkuy3czKtSEISG3zX29+Pouec3of1GLFuRatpdvtT675cWi6lu2G4p8lI/Tr6hs0kviYAo17uezSn9Ivj3mFuj4B2SrFy5/zl4p3/bjbEfiddTxCSdNq8yP0ynVBBD39PfIU9zx58G4g8ft1wGZNpoKh6VsbVSY/eA2UC7hLPI7FTqQmKIIMS6GhjOeopBXSAHa9z+SxDOkXiq31fleo5Z6w5x2pjy1Y3574jU3WtUn0GGiXgrFA07h64ZnxI6g34ouf+juGxhvEIaFnH8fJP2JwyjgzkqWf+yr87RKRSYbPjFsOteRaouyDbXlSjnKEacwP8kZLHX0xyrwubNjqhMWFzpFrzjcwJB4Au+TzVACmywWIv6+yYWcwiMa5k2b40LlAzJsH9A7dCG5I8CoggKqt41EnXrXaAvAuOI13CTHL0H+X+iuRb9q3CWPO9YQJvIphbgRE2yMQ6lKiQyOMI+0=
    on_success: change
    on_failure: always
